update

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,20 @@
-#!/usr/bin/python3
-python3 $PYFILE
+#!/bin/bash
+
+# Check if PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+  echo "PYFILE environment variable not set."
+  exit 1
+fi
+
+# Check if the Python file exists
+if [ ! -f "$PYFILE" ]; then
+  echo "Python file '$PYFILE' not found."
+  exit 1
+fi
+
+# Run the Python script
+python "$PYFILE"
+
+# Exit with status code of the Python script
+exit "$?"
 
